title:            Tankery
description:      Fly the Code
logo:             logo3.png
disqus_shortname: tankery
share:            true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
baseurl:       	  http://blog.tankery.me

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: \#18bc9c #80B3FF
  secondary: \#2c3e50 #FD6E8A
  highlight: \#01579B #FD6E8A
  secondary-dark: \#233140 #A2122F

# Fonts settings for site.
font:
  title: Montserrat, Hiragino Sans GB, Microsoft Yahei, WenQuanYi Micro Hei, sans-serif
  content: Open Sans, sans-serif
  links:
    - http://fonts.googleapis.com/css?family=Montserrat:400,700&amp;subset=latin,latin-ext
    - http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800,600&amp;subset=latin,latin-ext

# Owner/author information
owner:
  name:           Tankery Chen
  avatar:         tankery.jpg
  email:          tankery.chen@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Fly the Code, Fly my Life
  # Social networking links used in footer. Update and remove as you like.
  #twitter:        tankery_chen
  weibo:          1658528753
  facebook:       tankery.chen
  github:         tankery
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/+TankeryChen

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Featured Posts
    url: /featured
  - title: Categories
    url: /categories
  - title: About
    url: http://tankery.me/
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# markdown:    redcarpet
# highlighter: pygments

markdown:    kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Some settings for post
post_conf:
  more_tag:
    - <!--break-->
    - <!-- break -->
    - <!--more-->
    - <!-- more -->
  more_text: Read More...

gems: [jekyll-paginate]

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
